version: '3.3'
services:
    nginx-letsencrypt:
        image: jrcs/letsencrypt-nginx-proxy-companion
        container_name: nginx-letsencrypt
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ${DCP_ENV_NGINX_FILES_PATH}/certs:/etc/nginx/certs:rw
            - ${DCP_ENV_NGINX_FILES_PATH}/conf.d:/etc/nginx/conf.d
            - ${DCP_ENV_NGINX_FILES_PATH}/vhost.d:/etc/nginx/vhost.d
            - ${DCP_ENV_NGINX_FILES_PATH}/html:/usr/share/nginx/html
        env_file:
            - prod.env
