version: '3.3'
services:
    sslh:
        build: ./sslh
        ports:
            - "443:443"
        container_name: sslh
        environment:
            - HOST_LISTEN=0.0.0.0
            - PORT_LISTEN=443
            - SSH_HOST_FORWARD=dockerhost
            - SSH_PORT_FORWARD=${DCP_ENV_HOST_SSHD_PORT}
            - SSL_HOST_FORWARD=dockerhost
            - SSL_PORT_FORWARD=${DCP_ENV_NGINX_HTTPS_PORT}
        extra_hosts:
            - "dockerhost:${DCP_ENV_HOST_IP_ADDR}"
        env_file: prod.env

    traefik:
        image: traefik
        container_name: traefik
        ports:
            - "80:80"
            - "10443:443"
        networks:
            - web
        volumes:
            - ./traefik/traefik.toml:/etc/traefik/traefik.toml
            - ./traefik/acme.json:/acme.json
            - /var/run/docker.sock:/var/run/docker.sock:ro
        labels:
            - "traefik.enable=true"
            - "traefik.frontend.rule=Host:traefik.${DCP_ENV_DOMAIN}"
            - "traefik.basic.port=8080"

    gitea:
        image: gitea/gitea
        container_name: gitea
        ports:
            - "22:22"
        volumes:
            - gitea-volume:/data
            - ${DCP_ENV_GITEA_CONFIG_PATH}:/data/gitea/conf/app.ini
        env_file: prod.env
        labels:
            - "traefik.frontend.rule=Host:git.${DCP_ENV_DOMAIN}"
            - "traefik.port=3000"

    netdata:
        image: firehol/netdata
        container_name: netdata
        ports:
            - "19999:19999"
        volumes:
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
        cap_add:
            - SYS_PTRACE
        env_file: prod.env
        labels:
            - "traefik.frontend.rule=Host:netdata.${DCP_ENV_DOMAIN}"
            - "traefik.port=19999"

    matomo:
        image: matomo
        container_name: matomo
        links:
            - matomo-database:db
        env_file: prod.env
        labels:
            - "traefik.frontend.rule=Host:matomo.${DCP_ENV_DOMAIN}"
            - "traefik.port=80"

    matomo-database:
        image: mysql:5
        container_name: matomo-database
        volumes:
            - matomo-database-volume:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=${DCP_ENV_MATOMO_MYSQL_PASSWD}
        env_file: prod.env

    selfoss:
        image: jenserat/selfoss
        container_name: selfoss
        networks:
            - web
        volumes:
            - /srv/selfoss:/var/www/html/data
        env_file: prod.env
        labels:
            - "traefik.enable=true"
            - "traefik.frontend.rule=Host:rss.${DCP_ENV_DOMAIN}"
            - "traefik.basic.port=80"

    backup:
        build: ./backup
        ports:
            - "10022:22"
        container_name: backup
        volumes:
            - ./backup/backup.sh:/etc/periodic/daily/backup:ro
            - gitea-volume:/srv/backup/gitea/:ro
            - keeweb-webdav-volume:/srv/backup/keeweb-webdav/:ro
            - matomo-database-volume:/srv/backup/matomo-database/:ro
        environment:
            - DCK_LOCAL_BACKUP_REPO=/srv/backup
            - DCK_REMOTE_BACKUP_REPO=${DCP_ENV_REMOTE_BACKUP_REPO}

networks:
    web:
        external: true

volumes:
    gitea-volume:
    keeweb-webdav-volume:
    matomo-database-volume:
