version: '3.3'
services:
    nginx-proxy:
        image: jwilder/nginx-proxy:alpine-0.6.0
        container_name: nginx-proxy
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - ${NGINX_FILES_PATH}/certs:/etc/nginx/certs:ro
            - ${NGINX_FILES_PATH}/vhost.d:/etc/nginx/vhost.d
            - ${NGINX_FILES_PATH}/conf.d:/etc/nginx/conf.d
            - ${NGINX_FILES_PATH}/html:/usr/share/nginx/html
            - ./nginx-proxy/redirect.conf:/etc/nginx/conf.d/redirect.conf:ro
        env_file: prod.env
        labels:
            com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"

    keeweb:
        image: antelle/keeweb
        container_name: keeweb
        volumes:
            - ./keeweb/config.json:/keeweb/config.json:ro
        environment:
            - VIRTUAL_HOST=keeweb.${DOMAIN}
            - VIRTUAL_PORT=443
            - VIRTUAL_PROTO=https
            # uncomment to allow http
            # - HTTPS_METHOD=noredirect
            - LETSENCRYPT_HOST=keeweb.${DOMAIN}
        env_file: prod.env

    keeweb-webdav:
        build: ./keeweb-webdav
        container_name: keeweb-webdav
        volumes:
            - ./keeweb-webdav/httpd-dav.conf:/usr/local/apache2/conf/extra/httpd-dav.conf:ro
            - ./keeweb-webdav/user.passwd:/var/local/apache2/user.passwd:ro
        environment:
            - VIRTUAL_HOST=webdav.keeweb.${DOMAIN}
            # uncomment to allow http
            # - HTTPS_METHOD=noredirect
            - LETSENCRYPT_HOST=webdav.keeweb.${DOMAIN}
        env_file: prod.env

    selfoss:
        image: jenserat/selfoss
        container_name: selfoss
        volumes:
            - /srv/selfoss:/var/www/html/data
        environment:
            - VIRTUAL_HOST=rss.${DOMAIN}
            # uncomment to allow http
            # - HTTPS_METHOD=noredirect
            - LETSENCRYPT_HOST=rss.${DOMAIN}
        env_file: prod.env
