version: '3.3'
services:
    nginx-proxy:
        image: jwilder/nginx-proxy:alpine-0.6.0
        container_name: nginx-proxy
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - ${DCP_ENV_NGINX_FILES_PATH}/certs:/etc/nginx/certs:ro
            - ${DCP_ENV_NGINX_FILES_PATH}/vhost.d:/etc/nginx/vhost.d
            - ${DCP_ENV_NGINX_FILES_PATH}/conf.d:/etc/nginx/conf.d
            - ${DCP_ENV_NGINX_FILES_PATH}/html:/usr/share/nginx/html
            - ./nginx-proxy/redirect.conf:/etc/nginx/conf.d/redirect.conf:ro
        env_file: prod.env
        labels:
            com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"

    gogs:
        image: gogs/gogs
        container_name: gogs
        ports:
            - "10023:22"
        volumes:
            - gogs-volume:/data
            - ${DCP_ENV_GOGS_CONFIG_PATH}:/data/gogs/conf/app.ini
        environment:
            - VIRTUAL_HOST=git.${DCP_ENV_DOMAIN}
            - VIRTUAL_PORT=3000
            - HTTPS_METHOD=${DCP_ENV_HTTPS_METHOD}
            - LETSENCRYPT_HOST=git.${DCP_ENV_DOMAIN}
        env_file: prod.env

    keeweb:
        image: antelle/keeweb
        container_name: keeweb
        volumes:
            - ${DCP_ENV_KEEWEB_CONFIG_PATH}:/keeweb/config.json:ro
        environment:
            - VIRTUAL_HOST=keeweb.${DCP_ENV_DOMAIN}
            - VIRTUAL_PORT=443
            - VIRTUAL_PROTO=https
            - HTTPS_METHOD=${DCP_ENV_HTTPS_METHOD}
            - LETSENCRYPT_HOST=keeweb.${DCP_ENV_DOMAIN}
        env_file: prod.env

    keeweb-webdav:
        build: ./keeweb-webdav
        container_name: keeweb-webdav
        volumes:
            - ./keeweb-webdav/httpd-dav.conf:/usr/local/apache2/conf/extra/httpd-dav.conf:ro
            - ./keeweb-webdav/user.passwd:/var/local/apache2/user.passwd:ro
            - keeweb-webdav-volume:/var/www/${DCP_ENV_KEEWEB_DB_NAME}:rw
        environment:
            - VIRTUAL_HOST=webdav.keeweb.${DCP_ENV_DOMAIN}
            - HTTPS_METHOD=${DCP_ENV_HTTPS_METHOD}
            - LETSENCRYPT_HOST=webdav.keeweb.${DCP_ENV_DOMAIN}
        env_file: prod.env

    selfoss:
        image: jenserat/selfoss
        container_name: selfoss
        volumes:
            - /srv/selfoss:/var/www/html/data
        environment:
            - VIRTUAL_HOST=rss.${DCP_ENV_DOMAIN}
            - HTTPS_METHOD=${DCP_ENV_HTTPS_METHOD}
            - LETSENCRYPT_HOST=rss.${DCP_ENV_DOMAIN}
        env_file: prod.env

    backup:
        build: ./backup
        ports:
            - "10022:22"
        container_name: backup
        volumes:
            - ./backup/backup.sh:/etc/periodic/daily/backup:ro
            - keeweb-webdav-volume:/srv/backup/keeweb-webdav/:ro
        environment:
            - DCK_LOCAL_BACKUP_REPO=/srv/backup
            - DCK_REMOTE_BACKUP_REPO=${DCP_ENV_REMOTE_BACKUP_REPO}

volumes:
    gogs-volume:
    keeweb-webdav-volume:
